In [1]:
import data
train_data, val_data = data.get_data()

In [2]:
print(type(train_data))
print(type(val_data))

<class 'data.WrappedDataLoader'>
<class 'data.WrappedDataLoader'>


In [3]:
for v in train_data:
    print(type(v))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'li

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'li

In [457]:
import torch
import torch.nn as nn
seq_len = 3
batch_size = 2
input_size = 3
hidden_size = 4
num_layers = 1

rnn = nn.LSTM(input_size=input_size, hidden_size=hidden_size, num_layers=num_layers)
input = torch.randn(seq_len, batch_size, input_size)
h0 = torch.randn(num_layers, batch_size, hidden_size)
c0 = torch.randn(num_layers, batch_size, hidden_size)


In [459]:
output, (hn, cn) = rnn(input, (h0, c0))
print(output, output.shape)

tensor([[[-0.1743, -0.3897,  0.2436, -0.3180],
         [ 0.0216, -0.3419, -0.1148,  0.0673]],

        [[ 0.1390, -0.3280,  0.1396, -0.2998],
         [ 0.0837, -0.1846, -0.1262,  0.0567]],

        [[ 0.1329, -0.1007, -0.1101, -0.0489],
         [ 0.0473, -0.1574,  0.1053,  0.0378]]], grad_fn=<StackBackward>) torch.Size([3, 2, 4])


In [462]:
h, c = h0, c0
for i in range(seq_len):
    output, (h, c) = rnn(input[i:i+1], (h, c))
    print(output)

tensor([[[-0.1743, -0.3897,  0.2436, -0.3180],
         [ 0.0216, -0.3419, -0.1148,  0.0673]]], grad_fn=<StackBackward>)
tensor([[[ 0.1390, -0.3280,  0.1396, -0.2998],
         [ 0.0837, -0.1846, -0.1262,  0.0567]]], grad_fn=<StackBackward>)
tensor([[[ 0.1329, -0.1007, -0.1101, -0.0489],
         [ 0.0473, -0.1574,  0.1053,  0.0378]]], grad_fn=<StackBackward>)


In [26]:
class FC(nn.Module):
    def __init__(self):
        super(FC, self).__init__()
        self.fc = nn.Linear(10, 10)
        
    def forward(self, x):
        return self.fc(x.view(-1, 10))
    
class DoubleFC(nn.Module):
    def __init__(self, fc1, fc2):
        super(DoubleFC, self).__init__()
        self.fc1 = fc1
        self.fc2 = fc2
    
    def forward(self, x):
        return self.fc2(self.fc1(x))
    
model = FC()
input = torch.randn(2, 10)
output = model(model(input))
model1 = DoubleFC(model, model)
output1 = model1(input)
        

In [27]:
print(output)

print(output1)

tensor([[-0.5281,  0.4336,  0.1550, -0.3933, -0.7254,  0.2331,  0.4042,  0.5514,
          1.6942, -0.0480],
        [-0.4896,  0.1836,  0.4654,  0.1860, -0.0500,  0.4238,  0.4604, -0.1142,
          0.3605, -0.4412]], grad_fn=<AddmmBackward>)
tensor([[-0.5281,  0.4336,  0.1550, -0.3933, -0.7254,  0.2331,  0.4042,  0.5514,
          1.6942, -0.0480],
        [-0.4896,  0.1836,  0.4654,  0.1860, -0.0500,  0.4238,  0.4604, -0.1142,
          0.3605, -0.4412]], grad_fn=<AddmmBackward>)


In [85]:
class embedding(nn.Module):
    def __init__(self):
        super(embedding, self).__init__()
        self.embedding = nn.Embedding(10, 3)
        
    def forward(self, x):
        return self.embedding(x)
embedding = embedding()
input = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]])
output = embedding(input)
outsum = output.sum()
criterion = nn.MSELoss()
loss = criterion(outsum, torch.tensor(1.))
print(output)
loss.backward()
with torch.no_grad():
    for p in embedding.parameters():
        p -= p.grad * 0.01
output = embedding(input)
print(output)

tensor([[[-1.1406,  1.1802,  2.0050],
         [-0.4460,  0.5369, -0.7826],
         [ 0.2680,  0.3468,  0.3021],
         [-0.5293, -0.6633, -1.1283]],

        [[ 0.2680,  0.3468,  0.3021],
         [ 0.4108, -0.8212,  0.1958],
         [-0.4460,  0.5369, -0.7826],
         [ 1.3432, -0.5088, -0.2459]]], grad_fn=<EmbeddingBackward>)
tensor([[[-1.1316,  1.1893,  2.0141],
         [-0.4279,  0.5550, -0.7645],
         [ 0.2860,  0.3649,  0.3201],
         [-0.5203, -0.6542, -1.1193]],

        [[ 0.2860,  0.3649,  0.3201],
         [ 0.4199, -0.8121,  0.2048],
         [-0.4279,  0.5550, -0.7645],
         [ 1.3522, -0.4997, -0.2368]]], grad_fn=<EmbeddingBackward>)


In [72]:
for p in embedding.parameters():
    print(p.grad)


None


In [73]:
loss.backward()
for p in embedding.parameters():
    print(p.grad)

tensor([[0.0000, 0.0000, 0.0000],
        [3.0882, 3.0882, 3.0882],
        [6.1764, 6.1764, 6.1764],
        [3.0882, 3.0882, 3.0882],
        [6.1764, 6.1764, 6.1764],
        [3.0882, 3.0882, 3.0882],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [3.0882, 3.0882, 3.0882]])


In [74]:
for p in criterion.parameters():
    p -= p.grad * 0.01

    

In [57]:
for p in embedding.parameters():
    print(p.grad)

tensor([[0.0000, 0.0000, 0.0000],
        [0.1978, 0.1978, 0.1978],
        [0.3957, 0.3957, 0.3957],
        [0.1978, 0.1978, 0.1978],
        [0.3957, 0.3957, 0.3957],
        [0.1978, 0.1978, 0.1978],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.1978, 0.1978, 0.1978]])


In [75]:
output = embedding(input)
print(output)

tensor([[[ 0.2617, -0.9502,  1.2472],
         [ 1.1927, -0.5977,  0.8782],
         [-0.5657, -0.4323,  1.7233],
         [-0.1709,  0.4972, -1.4627]],

        [[-0.5657, -0.4323,  1.7233],
         [ 0.5992, -1.0104, -0.1046],
         [ 1.1927, -0.5977,  0.8782],
         [-0.2172,  0.2354, -0.7776]]], grad_fn=<EmbeddingBackward>)


In [68]:
criterion = nn.MSELoss()
a = torch.ones(3, 2, requires_grad=True)
b = a**2
c = b.sum()
loss = criterion(c, torch.tensor(1.))
print(a, a.grad)
print(b, b.grad)
loss.backward()
print(a, a.grad)
print(b, b.grad)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True) None
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>) None
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True) tensor([[20., 20.],
        [20., 20.],
        [20., 20.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>) None


In [102]:
torch.manual_seed(0)
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc = nn.Linear(5, 5)
        
    def forward(self, x):
        return self.fc(x.view(-1, 5))
criterion = nn.MSELoss()
model = Net()
input = torch.randn(1, 5)
for i in range(10):
    with torch.no_grad():
        x = model(input)
    output = model(x)
    loss = criterion(output.sum(), torch.ones(1, 1))
    print(loss.item())
    model.zero_grad()
    loss.backward()
    with torch.no_grad():
        for p in model.parameters():
            p -= p.grad * 0.01


0.4880531132221222
0.26262879371643066
0.14226491749286652
0.07744073122739792
0.04230573773384094
0.023172764107584953
0.012717668898403645
0.006989814341068268
0.003845837665721774
0.0021176787558943033


In [103]:
torch.manual_seed(0)
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc = nn.Linear(5, 5)
        
    def forward(self, x):
        return self.fc(x.view(-1, 5))
criterion = nn.MSELoss()
model = Net()
input = torch.randn(1, 5)
for i in range(10):
    x = model(input)
    output = model(x)
    loss = criterion(output.sum(), torch.ones(1, 1))
    print(loss.item())
    model.zero_grad()
    loss.backward()
    with torch.no_grad():
        for p in model.parameters():
            p -= p.grad * 0.01

0.4880531132221222
0.19338180124759674
0.07292622327804565
0.026400910690426826
0.009282544255256653
0.0032016343902796507
0.0010910972487181425
0.0003691470483317971
0.00012435180542524904
4.17856645071879e-05


In [311]:
embedding = nn.Embedding(10, 3)
input = torch.randint(10, (12, 2))
print(input, input.size())
output = embedding(input)
print(output.size())

tensor([[2, 2],
        [6, 3],
        [0, 6],
        [1, 4],
        [7, 0],
        [8, 0],
        [8, 1],
        [1, 5],
        [8, 6],
        [4, 1],
        [4, 2],
        [9, 2]]) torch.Size([12, 2])
torch.Size([12, 2, 3])


In [145]:
output = embedding(input)
print(output.size())

torch.Size([1, 1, 3])


In [140]:
output = torch.unsqueeze(output, dim=0)
print(output.size())

torch.Size([1, 1, 3])


In [184]:
classifier = nn.Linear(5, 3)
input = torch.randn(1, 2, 3, 5)
output = classifier(input)
print(output.size())

torch.Size([1, 2, 3, 3])


In [238]:
weights = torch.randn(1, 1, 5)
weights = torch.squeeze(weights, dim=0)
print(weights)

tensor([[-0.2571,  0.0774, -0.4484,  0.0732,  0.8024]])


In [239]:
weights = nn.functional.softmax(weights, dim=-1)
print(weights)

tensor([[0.1333, 0.1863, 0.1101, 0.1855, 0.3847]])


In [240]:
choices = [0] * 5
for i in range(2000):
    choice = torch.multinomial(weights, 1)
    # print(choice, choice.shape)
    choices[choice] += 1
print(np.array(choices) / 2000)

[0.146  0.168  0.1275 0.172  0.3865]


In [247]:
choice = torch.multinomial(weights, 1)
print(choice, choice.shape)

tensor([[1]]) torch.Size([1, 1])


In [242]:
choice = torch.unsqueeze(choice, dim=0)
print(choice, choice.shape)

tensor([[[4]]]) torch.Size([1, 1, 1])


In [250]:
stacked = torch.stack([choice, choice], dim=0)
print(stacked, stacked.shape)

tensor([[[1]],

        [[1]]]) torch.Size([2, 1, 1])


In [261]:
weights = torch.randn(1, 2, 5)
weights = torch.squeeze(weights, dim=0)
weights = nn.functional.softmax(weights, dim=-1)
print(weights)
choices = torch.zeros(2, 5)
for i in range(2000):
    choice = torch.multinomial(weights, 1) 
    for j in range(2):
        choices[j][choice[j]] += 1
print(np.array(choices) / 2000)

tensor([[0.0923, 0.0886, 0.7134, 0.0335, 0.0722],
        [0.2794, 0.2534, 0.1812, 0.1343, 0.1517]])
[[0.089  0.088  0.7185 0.0375 0.067 ]
 [0.2885 0.2555 0.1745 0.131  0.1505]]


In [262]:
print(choice, choice.shape)

tensor([[2],
        [2]]) torch.Size([2, 1])


In [263]:
print(choice.item())

ValueError: only one element tensors can be converted to Python scalars

In [259]:
a = torch.randint(
            3, (1, 1)
            )
print(a.shape)

torch.Size([1, 1])


In [260]:
b = torch.tensor([[0]])
print(b.shape)

torch.Size([1, 1])


In [277]:
a = torch.randn(2, 1, 2)
b = a.expand(2, 3, 2)
print(b, b.size())

tensor([[[ 0.6537, -0.7391],
         [ 0.6537, -0.7391],
         [ 0.6537, -0.7391]],

        [[ 1.1864,  1.2771],
         [ 1.1864,  1.2771],
         [ 1.1864,  1.2771]]]) torch.Size([2, 3, 2])


In [294]:
a = [1, 2, 3, 4, 9, 0]
b = torch.tensor(a)
print(b, b.size(1))

RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [302]:
a = torch.randn(2, 3, 4)
b = torch.zeros(2, 3, 4)
print(b)
for i in range(2):
    b[i] = a[i]
print(b)
a[0][0][0] = 100
print(a)
print(b)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[ 2.4293, -0.5426,  0.6427, -0.1823],
         [-0.4642, -1.0604,  0.0463, -0.4603],
         [-0.5376, -0.2774, -0.9089,  0.7470]],

        [[ 1.7302,  0.2825, -1.3170,  0.3935],
         [ 0.8415,  0.2301, -0.8241, -1.3128],
         [-1.4545, -0.1590, -0.2946, -1.8067]]])
tensor([[[ 1.0000e+02, -5.4264e-01,  6.4267e-01, -1.8230e-01],
         [-4.6424e-01, -1.0604e+00,  4.6288e-02, -4.6026e-01],
         [-5.3764e-01, -2.7737e-01, -9.0891e-01,  7.4699e-01]],

        [[ 1.7302e+00,  2.8251e-01, -1.3170e+00,  3.9352e-01],
         [ 8.4154e-01,  2.3011e-01, -8.2408e-01, -1.3128e+00],
         [-1.4545e+00, -1.5901e-01, -2.9463e-01, -1.8067e+00]]])
tensor([[[ 2.4293, -0.5426,  0.6427, -0.1823],
         [-0.4642, -1.0604,  0.0463, -0.4603],
         [-0.5376, -0.2774, -0.9089,  0.7470]],

        [[ 1.7302,  0.2

In [301]:
a = torch.randn(2, 3, 4)
b = a[0]
print(a)
print(b)
print(a.shape, b.shape)
b[0] = torch.zeros(1, 4)
print(a)
print(b)

tensor([[[-0.0066, -0.8912, -0.5735, -1.3809],
         [ 0.2871,  0.1870, -0.9990,  1.7835],
         [-1.0054,  0.9734, -0.8469,  1.0602]],

        [[ 0.8966,  0.1567,  0.7560,  0.2788],
         [-0.7966,  0.9568, -0.8430, -0.4533],
         [ 0.9405, -0.6994, -1.8327, -0.6051]]])
tensor([[-0.0066, -0.8912, -0.5735, -1.3809],
        [ 0.2871,  0.1870, -0.9990,  1.7835],
        [-1.0054,  0.9734, -0.8469,  1.0602]])
torch.Size([2, 3, 4]) torch.Size([3, 4])
tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.2871,  0.1870, -0.9990,  1.7835],
         [-1.0054,  0.9734, -0.8469,  1.0602]],

        [[ 0.8966,  0.1567,  0.7560,  0.2788],
         [-0.7966,  0.9568, -0.8430, -0.4533],
         [ 0.9405, -0.6994, -1.8327, -0.6051]]])
tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.2871,  0.1870, -0.9990,  1.7835],
        [-1.0054,  0.9734, -0.8469,  1.0602]])


In [410]:
a = [1, 2, 3]
b = [4, 5, 6]
ab = [a, b]
c = list(zip(*ab))
print(c)
d = [torch.tensor(v) for v in c]
print(d)
print(d[0].shape)

[(1, 4), (2, 5), (3, 6)]
[tensor([1, 4]), tensor([2, 5]), tensor([3, 6])]
torch.Size([2])


In [319]:
print(d, d.shape)
e = d.unsqueeze(dim=0)
print(e, e.shape)

tensor([[1, 4],
        [2, 5],
        [3, 6]]) torch.Size([3, 2])
tensor([[[1, 4],
         [2, 5],
         [3, 6]]]) torch.Size([1, 3, 2])


In [419]:
rollout = torch.randint(3, (2, 1))
logits = torch.randn(2, 4)
print(rollout, rollout.shape)
print(logits, logits.shape)

tensor([[1],
        [2]]) torch.Size([2, 1])
tensor([[ 0.8810, -1.5047,  0.9831, -1.8671],
        [-0.2430, -1.4192, -0.7649, -1.2342]]) torch.Size([2, 4])


In [420]:
p = torch.gather(logits, -1, rollout)

In [399]:
print(p, p.shape)

tensor([[0.1133],
        [1.2930]]) torch.Size([2, 1])


In [ ]:
t = torch.tensor([[1,2],[3,4]])
>>> torch.gather(t, 1, torch.tensor([[0,0],[1,0]]))

In [416]:
a = [1, 2, 3]
b = 0
a[:-1].insert(0, b)
print(a)

[1, 2, 3]


In [431]:
a = [1, 2, 3]
b = [4, 5, 6]
ab = [a, b]
[torch.tensor(v) for v in list(zip(*ab))]

[tensor([1, 4]), tensor([2, 5]), tensor([3, 6])]

In [426]:
a = torch.rand(2, 3)
print(a, a.shape)
b = torch.log(a)
print(b, b.shape)

tensor([[0.4676, 0.5432, 0.1430],
        [0.0796, 0.8830, 0.8347]]) torch.Size([2, 3])
tensor([[-0.7601, -0.6103, -1.9451],
        [-2.5304, -0.1245, -0.1807]]) torch.Size([2, 3])


In [446]:
a = torch.randn(2, 1)
b = torch.randn(2, 1)
print(a, a.shape)
print(b, b.shape)

tensor([1.3283, 0.3076]) torch.Size([2])
tensor([[ 0.4061],
        [-1.1511]]) torch.Size([2, 1])


In [447]:
c = a * b
print(c, c.shape)

tensor([[ 0.5394,  0.1249],
        [-1.5290, -0.3541]]) torch.Size([2, 2])


In [450]:
a = torch.randn(2, 1)
b = a.mean()
print(a)
print(b)

tensor([[-0.2465],
        [-1.0667]])
tensor(-0.6566)


In [451]:
rollout_buffer = [[1, 2, 3], [4, 5, 6]]
reward_buffer = [0.2, 0.8]
rollout_list = [torch.tensor(v) for v in list(zip(*rollout_buffer))]
reward_batch = torch.tensor(reward_buffer)
print(rollout_list)
print(reward_batch)

[tensor([1, 4]), tensor([2, 5]), tensor([3, 6])]
tensor([0.2000, 0.8000])


In [467]:
para_space = {
    "activation_num_int_bits": (1, 2, 3, 4, 5),
    "activation_num_frac_bits": (0, 1, 2, 3, 4, 5, 6, 7),
    "weight_num_int_bits": (0, 1, 2, 3, 4, 5),
    "weight_num_frac_bits": (1, 2, 3, 4, 5, 6, 7)
    }
a, b = zip(*para_space.items())

In [472]:
print(b)

((1, 2, 3, 4, 5), (0, 1, 2, 3, 4, 5, 6, 7), (0, 1, 2, 3, 4, 5), (1, 2, 3, 4, 5, 6, 7))


In [471]:
para_space.items()

dict_items([('activation_num_int_bits', (1, 2, 3, 4, 5)), ('activation_num_frac_bits', (0, 1, 2, 3, 4, 5, 6, 7)), ('weight_num_int_bits', (0, 1, 2, 3, 4, 5)), ('weight_num_frac_bits', (1, 2, 3, 4, 5, 6, 7))])

In [476]:
tuple(len(v) for v in b)

(5, 8, 6, 7)

In [477]:
a = [1, 2, 3]
a.clear()
print(a)

[]


In [482]:
a = True
print(type(a))

<class 'bool'>


In [484]:
if type(a) is bool:
    print(True)

True


In [486]:
fc = nn.Linear(3, 1)
a = torch.randn(2, 3)
print(fc(a).shape)

torch.Size([2, 1])
